### PR TITLE
change checkmark from lightly prepackaged to lightly git

### PR DESCRIPTION
**Pull request by Goodname15**
Screenshot_20220731_140026

### CODE REVIEW

**Comment by doncsugar** [comment]
Looks good!

I do have a question: Are you using Git Lightly or an older pre-packaged version?

This is how the newer Lightly looks:
image

Should I merge it and make 2 versions?

**Comment by Goodname15** [comment]
Oh, I see. Was wondering if the git Version was any different...
Yeah, I'm using the prepackaged Version because the Git Version doesn't work on Fedora 36 (you can compile it, but then you can't select it.
(https://github.com/Luwx/Lightly/issues/156)

**Comment by Goodname15** [comment]
> Should I merge it and make 2 versions?

For this one change alone, I don't think it makes sense, but if I (or someone else) does the other changes maybe it would.

As far as I can tell, the only difference between the two Versions is the checkmark icon and the bars
Screenshot_20220802_085259

**Comment by doncsugar** [comment]
I'll make the needed changes in a bit. Personally, I'm not a fan of the new smaller slider/progress bars, though they are more readable.

If you haven't tried the git version in a while, give it another try if you want. I remember something like that bug on a Fedora machine and now Lightly works again.

**Pull request merged**
